name: release

on:
  push:
#    branch: master
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - run: |
            sudo apt-get install gcc-multilib g++-multilib gcc-mingw-w64 libxinerama-dev xorg-dev mingw-w64 libx11-dev mesa-common-dev libglu1-mesa-dev

      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.1
          check-latest: true
      - uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}